name: 'Emacs Lisp check'
description: |
  Run a number of different Emacs Lisp checks.
inputs:
  check:
    description: |
      Check expression that should be run.
      Consult the README for supported checks.
    default: 'melpa'
  file:
    description: |
      Entry file for Emacs Lisp checks.
      Basic globbing is supported.
    default: '*.el'
  ignore_warnings:
    description: |
      Whether to ignore warnings.
    default: false
  warnings_as_errors:
    description: |
      Whether to treat errors as warnings.
    default: false
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'align-left'
  color: 'purple'
