name: "test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: purcell/setup-emacs@master
    - uses: ./
  test-global:
    runs-on: ubuntu-latest
    steps:
    - uses: purcell/setup-emacs@master
    - uses: leotaku/emacs-action@master

