name: test

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test-on-self:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs:
          - 24.1
          - 24.2
          - 24.3
          - 24.4
          - 24.5
          - 25.1
          - 25.2
          - 25.3
          - 26.1
          - 26.2
          - 26.3
          - snapshot
    steps:
    - uses: actions/checkout@v2
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs }}
    - uses: ./
  test-on-simple:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: leotaku/theist-mode
    - uses: purcell/setup-emacs@master
      with:
        version: 26.3
    - uses: leotaku/elisp-check-action@master
