name: test

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test-on-self:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - snapshot
          - 26.3
          - 26.2
          - 26.1
          - 25.3
          - 25.2
          - 25.1
          - 24.5
          - 24.4
          - 24.3
          - 24.2
          - 24.1
        ignore_warnings:
          - true
        include:
          - emacs_version: snapshot
            ignore_warnings: false
    steps:
    - uses: actions/checkout@v2
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: ./
      with:
        file: elisp-check.el
        check: melpa
        ignore_warnings: ${{ matrix.ignore_warnings }}
