name: "test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test-on-self:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs: [ snapshot, 26.3, 26.2, 26.1, 25.3, 25.2, 25.1 ]
    steps:
    - uses: actions/checkout@v2
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs }}
    - uses: ./
